version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"


    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

volumes:
  postgres_data:
