# Generated by Django 4.2.1 on 2023-05-17 14:52

import commentary_app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("homepage", models.URLField(blank=True)),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="comments/images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "gif"]
                            )
                        ],
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to="comments/files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["txt"]
                            ),
                            commentary_app.models.validate_file_size,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="commentary_app.comment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
